---
title: 'B3 is shutting down its ftp site'
subtitle: "Impact in CRAN packages"
author: "Marcelo S. Perlin"
date: '2019-07-01'
draft: false
tags: ["R", "GetHFData"]
categories: ["R", "GetHFData"]
---

```{r, echo = FALSE}
knitr::opts_chunk$set(message = FALSE, cache = TRUE)
```

**Well, bad news travels fast. **

Over the last couple of weeks I've been receiving a couple of emails regarding B3's [decision](http://www.b3.com.br/data/files/40/76/60/59/745666102F630666AC094EA8/CE%20018-2019%20-%20Prorroga%C3%A7%C3%A3o%20do%20Prazo%20de%20Desativa%C3%A7%C3%A3o%20do%20Servior%20FTP.pdf) of shutting down its [ftp site](ftp://ftp.bmf.com.br/). More specifically, users are eager to know how it will impact my data grabbing packages in CRAN. I'll use this post to explain the situation for everyone.

The only package affected directly will be `GetHFData`, which uses the ftp site for downloading the raw zipped files with trades and quotes. The main function will no longer work as all internet files are not available. However, the function that reads the local files, `GetHFData::ghfd_read_file()`, will still work as long as you have the files available in your computer. 

Soon I'll release an update to `GetHFData` that will bypass the ftp checking process. Users will be able to load up the code with local files. Btw, before anyone asks, I'm not aware of any other site that distributes the zipped files. In this topic, everyone should know that B3's web policy does not allow the redistribution of their data. 

As for my personal opinion on the event, B3 is a private company and can do whatever they want with their data. In fact, it is standard for many international exchanges to sell their high-frequency trade&quote data. However, I fell that they could still offer a free sample of past raw data for students and researchers, keeping `GetHFData` alive. I'm not sure how this would hurt their business. In fact, it is easy to argue that the "free" training would help them. 

On the research side, studying microstructure of the Brazilian financial market will become even more difficult now, without easy access to the datasets. 

As a clever stoic man once said, we should only worry about things we can control. 

Life (and research) goes on..

