---
title: "Financial Datasets Available in the Website"
author: "Marcelo S. Perlin"
date: '2020-04-20'
draft: no
subtitle: ' '
tags:
- R
categories:
- R
---

I've been researching financial data for over 10 years and gathered a great deal of compiled tables. Most of these comes from my R packages and have been used for creating class material, doing [research](https://www.msperlin.com/blog/publication/) and even [writing a book](https://www.msperlin.com/blog/publication/2019_book-pirf/). These files were mostly found in many copies across different projects. 

Last week I started to organize and centralize all my data files and noticed how valuable these tables could be for other researchers and teachers. 

As of today, I'll be hosting all public compiled data in my [dataverse website](https://dataverse.harvard.edu/dataverse/msperlin). Most of them are the product of using my R packages in a large scale data grabbing process. For example, I used package `BatchGetSymbols` to download daily prices of all stocks belonging to the SP500 since 2015 and saved it in a .csv file. 

Hope you find these files as useful as they were to me. If you use it for writing a report, make sure to cite the package as the source of data (see the _Readme.txt_ file in each folder  for details). 