---
title: "New online book available - Poupando e Investindo em Renda Fixa"
author: "Marcelo S. Perlin"
date: '2020-05-24'
draft: no
subtitle: ' '
tags:
- pirf
- investing
categories:
- pirf
- investing
---

Back in early 2019 I decided to try a new writing style, resulting in my book about investing. The main innovation is the use of real data to make conclusions about the best way to invest money in the fixed income market in Brazil. 

I was a lot of fun to learn more and write about money management and investing, a subject so different from the usual programming topics dealt in this blog. The audience is also much larger, making it a more challenging and rewarding effort. 

I'm happy to report that the feedback has been great. As of today, 2020-05-24, the book has 22 five star ratings in [Amazon](https://www.amazon.com.br/dp/B07RR9K9PV), a remarkable achievement!

Today I decided to work and publish the online version of the book. The content for the first three chapters is available at [https://www.msperlin.com/pirf/](https://www.msperlin.com/pirf/). Hope you like it. If you do, please leave a feedback at Amazon.com.







