---
title: "Ten years as a professor -- six advices to young academics"
author: "Marcelo S. Perlin"
date: '2021-03-10'
tags:
- R
- personal
categories:
- R
- personal
draft: no
---

In the 18th of march 2021 I'll complete exactly ten years since finishing my PhD and taking a professorship position at UFRGS, south of Brazil. In this post I'll write about what I learned during this period and, hopefully, help other academics that are just starting out. 

This post is the summary of a talk I had with a former PhD student. I'm fully aware that academic work can be very different across countries and institutions. I don't claim to have all the answers to all the problems. But, these are a couple of advice that would certainly help me in my starting years. 


### 1) Find a hobby

First and foremost, find a hobby. Yes, sounds weird as a first advice but you would be surprised how a hobby -- or anything that takes your mind of work -- can give you a great boost in quality of life and work, specially in academia. 

A good hobby should not be related to work, or driven by its consequences. For example, I usually go to the gym twice a week. Not because I enjoy it, but due to the fact that it helps me keeping my body healthy. Honestly, I don't like gyms, but I go anyway. 

Said that, sports are a good example of hobbies. You do it for its own sake. So, find a sport you like and invest time in it. You'll thank me later.


### 2) Plan for the long term

One repeated mistake I made in my starting years is to enroll in many different projects. In hindsight, I can see that most of them were doomed to fail before even starting. At first, everyone is excited to join and do something new, but few remain if their motivation is not right. Moreover, students have a tendency to say yes to the teacher, which makes them to agree to projects that they might not be really interested. Everyone will stay in the project until time becomes scarce or something new shows up. 

Incentives play a key role in everything we do and I learned this the hard way. For example, if a student works 8 hours in a bank, he is not taking a weekend off to review the econometrics of that scientific paper we wrote together months ago. And there is nothing wrong with that. The mistake was from my part for 1) not making it clear of how much work a paper needs and 2) assuming the student and I would share the same incentives, which is simply not true. 

When playing for the long term academic game, focus on things that you are likely to continue doing in 5, 10, 15 years:

- Make a personal website (yes, many people still don't). Without it, how will people see your work? 
- Find a research topic that you're passionate about; this way will be much easier to write, teach and code about the topic. 
- Find colleagues that are also playing the long term game and work with them.
- Use open software in data analysis and teaching, preferably Python or R. Its smart to keep your workflow reproducible and license-free. This way you'll be able to take your work anywhere, if necessary;
- Don't ever compromise your reputation. A famous quote: "it takes years to build a reputations and a few minutes to lose it".
- Learn new tools: linux, server-side scripting, building websites, editing videos, using YouTube, using e-learning platforms, and so on. Whatever it takes to deliver your work to society. Don't let other people do it for you. You have the time, just site down and learn it. 


### 3) Quantity beats quality 

One statistic that few people know is that, for a reputable, high ranking journal such as _Journal of Finance_, the median number of citations per article is close to zero. This means that, what drives the high impact factors of such journals is a couple of papers that become popular in their field of expertise. This means that few articles get all the glory. 

Also know as the _tail effect_ or _Pareto rule_, this is a common pattern in business. As an example, there were many search engines before Google but none with its success. The high scalability of business in digital commodities, such as search engines, makes it so that a couple of companies gets all the sales (or search queries). Likewise, if you invest in a portfolio of companies over a long period of time, your total performance would be due to a handful of companies. Those winners with the highest returns will easily compensate for losers, and still give you a handsome financial reward.     

This is also true for your research work. If you write ten papers, be glad that one of them does well and attracts citations. This might also just be good luck, due to right timing. This means that you should focus your research in quality, but also **quantity**. The more papers, higher the likelihood of hitting the spot and getting recognition. 


### 4) Its not all about papers, but it helps 

Papers have historically been the main output of academics. I certainly felt that way when starting out. Today, the university work can take many different shapes and colors. You can contribute to society not just by writing research papers but also:

- writing and publishing code
- writing books
- writing news articles
- writing blog posts 
- releasing videos on YouTube
- local lectures

My suggestion is to try as many as possible and see which type of output you like best. 


### 5) You have freedom and autonomy, use it..

Academics generally have the autonomy to define their workflow and control their environment. Use and abuse of that freedom. Very few people have that kind of autonomy and some would probably be willing to pay a good amount of money for it, if they could. With that in mind:

- Its not about the number of hours, but what you do with them. No one cares about how many hours you are at the university, but what you are producing to society, whether it is research articles, lectures or code.
- Change your working hours as needed. For example, if you live in a large city, why do you need to get from/to work at rush hours? Likewise, why not working on the weekend and taking Monday off? (I've done this countless times -- its fun..)
- Don't work with people you don't like. Easier said than done, but keep in mind that you always have that choice.
- Learn to say no, constantly. 


### 6) Academia is changing, fast..

And you should be worried. Historically, universities always had the prestige of being knowledge centers. In contrast, knowledge is now abundant in the digital world. My students are no longer learning by reading books, but by watching YouTube videos or using other platforms. It seems we distanced ourselves from the real world and that is starting to backfire. A reliable sign is a [trend](https://www.cnbc.com/2018/08/16/15-companies-that-no-longer-require-employees-to-have-a-college-degree.html) in the hiring process of companies of not requiring a college degree, but only proof of work. 

The change is coming and we have not clue of how universities will adapt in the next 5, 10 years. The only thing you can control is how much you learn and do. So, do more and learn more. Be prepared.

