---
title: "Looking back at 2022-2023 and plans for 2024"
author: "Marcelo S. Perlin"
date: '2023-12-29'
draft: false
subtitle: ' '
tags: ["R", "looking back"]
categories: ["R", "personal"]
---

```{r, echo=FALSE}
this_year <- 2023
previous_blog_link <- "https://msperlin.com/post/2022-12-29-looking-back-2022/"
```

Another year has passed and now its time to discuss what happened in this cycle, along with future projects. 

Year 2023 passed by very quickly, and I'm grateful for everything I've learned ane experienced. Here are the highlights from my work.

---

# Highlights of `r this_year` and `r this_year-1`

## Academic Papers

I co-authored a single academic papers during this period:

- [What is the sustainable withdraw rate for Brazil?](https://periodicos.fgv.br/rbfin/article/view/89040)

However, many papers are ready (or almost ready) for submission. I expect that 2024 will be a year with many publications.

## Books

- I revised book [Analyzing Financial and Economic Data with R](https://msperlin.com/publication/2023_book-afedr-en/) for its second edition. Most of the changes are in the background, with the use of Quarto technology for [books](https://quarto.org/docs/books/). 

- I wrote and published book [Questões de R em Concursos Públicos](https://msperlin.com/publication/2023_book-qrcp/), containing several questions about R used in public examinations in Brazil.


## R Packages

Nothing special to report here, besides the usual maintainence of current packages.

---

# Checking previous plans

At the end of `r this_year-1`, my plans for `r this_year` [were](`r previous_blog_link`):

Publish revision of _Analyzing Financial and Economic Data with R_
: Done! The new edition is published in [Amazon](https://www.amazon.com/Analyzing-Financial-Economic-Data-R/dp/171062731X)

Publish revision of _Análise de Dados Financeiros e Econômicos com o R_
: Not done! The revision will be up in early 2024, and probably distributed as two separate books, one as an introduction to R and other as Data Analysis with R.

Write and publish paper about research schollarships
: The paper is already submitted to a high impact journal. This is a very interesting paper, with impactful results. I hope that soon I'll be able to write about it in the blog.

---

# Plans for `r this_year+1`

Publish revision of _Análise de Dados Financeiros e Econômicos com o R_
: My book in R is likely to be separated into two distinct books, one as "An introduction to R", and other as "Data Analysis with R".

Paper "Using ChatGPT for  creating multi-language finance related sentiment dictionaries"
: co-authored with Marcos Reichert, this paper is submitted and likelly to be published in 2024.

Paper "Risk forecasting comparisons in decentralized finance: An approach in constant product market makers"
: co-authored with Lucas Mussoi and Fernanda Muller, this paper is also submitted and likelly to be published in 2024.